semgrep:
  name: Semgrep
  runs-on: [self-hosted]
  runs:
    using: "composite"
    steps:
      - uses: actions/checkout@v2
      - uses: returntocorp/semgrep-action@v1
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          publishDeployment: 339
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}